# serverless.yml

component: website
name: blog
# org: test
app: blog
stage: dev

inputs:
  src:
    src: ./src
    # dist: ./dist
    # hook: npm run build
    index: index.html
    error: index.html
  region: ap-shanghai
  bucketName: blog-bucket
  protocol: https
  replace: true # 是否覆盖式部署
  disableErrorStatus: false # 是否禁用错误码，默认 false
  autoSetupAcl: true # 自动配置 bucket 访问权限为 “公有读私有写”
  autoSetupPolicy: false # 自动配置 bucket 的 Policy 权限为 “所有用户资源可读”
  # env: # 配置前端环境变量
  #   API_URL: https://api.com
  hosts:
    - host: www.iamzs.top
      async: true # 是否同步等待 CDN 配置。配置为 false 时，参数 autoRefresh 自动刷新才会生效，如果关联多域名时，为防止超时建议配置为 true
      area: overseas # mainland, overseas, global
      autoRefresh: true #开启自动 CDN 刷新，用于快速更新和同步加速域名中展示的站点内容
      onlyRefresh: false #建议首次部署后，将此参数配置为 true，即忽略其他 CDN 配置，只进行刷新操作
      https:
        switch: on
        http2: on
        certInfo:
          certId: 'hcSR9hVm'
      cache:
        simpleCache:
          followOrigin: on
          cacheRules:
            - cacheType: all
              cacheContents:
                - '*'
              cacheTime: 1000
      forceRedirect:
        switch: on
        redirectType: https
        redirectStatusCode: 301
  # cors:
  #   # - allowedOrigins:
  #   #     - '*.tencent.com'
  #   #     - '*.qcloud.com'
  #   #   allowedMethods:
  #   #     - PUT
  #   #     - POST
  #   #     - DELETE
  #   #     - HEAD
  #   #   allowedHeaders: '*'
  #   #   maxAgeSeconds: 0
  #   - allowedOrigins:
  #       - '*'
  #     allowedMethods:
  #       - GET
  #       - PUT
  #       - POST
  #       - DELETE
  #       - HEAD
  #     allowedHeaders: '*'
  #     maxAgeSeconds: 0